### ISSUE TITLE
BUG 使用QNUploadManager的puData方法返回值错误

### ISSUE THREAD

**Issue by molezzz** [qiniu/objc-sdk#183]
使用QNUploadManager的putData方法，当token错误时服务器端没有返回 403，而是返回了 400  file is not specified in multipart

**Comment by longbai** [comment]
收到，我们跟进下

**Comment by longbai** [comment]
麻烦给下请求的具体参数

**Comment by jiaojunjiahanlin** [comment]
我大体测试了下，设置token为nil,直接返回token 没设置的错误，本地报错，设置token有错误，例如ak不正确，直接bad token，设置token中的签名部分少了个字符，直接异常：2016-06-15 10:58:51.952 test[31038:4833598] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: 'data parameter is nil'


大体可以看出你说的问题，应该是本地报错，而不是服务端报错，其次你的token是服务端签发，代码生成为何会出错，应该从自身解决。

**Comment by peaceful321** [comment]
最好能走工单，提供一下token给我们查看一下；
